swagger: '2.0'
info:
  title: HerpDerp
  description: Draft Spec
  version: 0.0.1
host: localhost
schemes:
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  /widgets:
    get:
      summary: Widgets
      description: The widgets endpoint returns cues for a given user
      parameters:
        - name: project_id
          in: query
          description: Limit widgets by project id
          required: false
          type: number
      responses:
        '200':
          description: An array of widgets
          schema:
            type: array
            items:
              $ref: '#/definitions/Widget'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Widgets
      description: creates a new widget
      parameters:
        - name: widget
          in: body
          schema:
            $ref: '#/definitions/Widget'
      responses:
        '200':
          description: A widget object

definitions:
  Widget:
    type: object
    properties:
      id:
        type: number
        description: the unique identifier of a widget
      stock_number:
        type: string
        description: A human-readable identifier for a widget
      name:
        type: string
        description: Display name of widget.
      storage_key:
        type: string
        description: Link to CDN of media.
      project_id:
        type: integer
        description: The id of the Project containing the cue
